ReferenceError: CardFooter is not defined     at PricingPage (rsc://React/Server/file:///home/user/studio/.next/server/chunks/ssr/_fd54b90c._.js?63:641:285)     at resolveErrorDev (https://6000-firebase-studio-1746845803293.cluster-3gc7bglotjgwuxlqpiut7yyqt4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17512:48)     at processFullStringRow (https://6000-firebase-studio-1746845803293.cluster-3gc7bglotjgwuxlqpiut7yyqt4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17728:23)     at processFullBinaryRow (https://6000-firebase-studio-1746845803293.cluster-3gc7bglotjgwuxlqpiut7yyqt4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17716:9)     at progress (https://6000-firebase-studio-1746845803293.cluster-3gc7bglotjgwuxlqpiut7yyqt4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17862:102)     at InnerLayoutRouter (https://6000-firebase-studio-1746845803293.cluster-3gc7bglotjgwuxlqpiut7yyqt4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_1a6ee436._.js:351:55)     at OuterLayoutRouter (https://6000-firebase-studio-1746845803293.cluster-3gc7bglotjgwuxlqpiut7yyqt4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_1a6ee436._.js:498:73)
fix and can the nav bar show all the nav bar elements?? I expect you to put copy trading under the trading section